//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MVCStok.Models.Entity


{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMüsteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMüsteriler()
        {
            this.TblStok = new HashSet<TblStok>();
        }
    
        public int MusteriId { get; set; }

        [Required(ErrorMessage ="Bu alanı boş bırakamzsınız...")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik isim gir bacım")]
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStok> TblStok { get; set; }
    }
}
