//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStok
    {
        public int SatısId { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> Müsteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual TblMüsteriler TblMüsteriler { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
